### ISSUE TITLE
Pull from userId

### ISSUE THREAD

**Issue by Deelite310** [potomak/jquery-instagram#11]
I have this installed, but I can't get anything when I call for userId.

Here is my call to the function:

<script>
    $(document).ready(function() {

$(".instagram.cid").instagram({
        userId: 'my_user_id',
        show: 5,
        clientId: clientId
      });

});
  </script>

And my div:

<div class="instagram cid"></div>

It doesn't populate.

**Comment by rtaibah** [comment]
I am having the same issue. Thought I was crazy!

**Comment by potomak** [comment]
I can confirm this error. It's due to an auth error for `/users/{user-id}/media/recent` API endpoint.

Trying to run:

``` javascript
$(".instagram.tag").instagram({
  userId: 2613914, // my user id
  show: 5,
  clientId: 'baee48560b984845974f6b85a07bf7d9' // example app's client id 
});
```

results in this error:

``` json
{
  "meta":{
    "error_type":"OAuthParameterException",
    "code":400,
    "error_message":"\"access_token\" URL parameter missing. This OAuth request requires an \"access_token\" URL parameter."
  }
}
```

At http://instagram.com/developer/authentication/ there are no clues about authorization request because `/users/{user-id}/media/recent` API endpoint is not user specific like `/users/self/feed` but in general there are no explicit informations about endpoints required auth.

**Comment by Deelite310** [comment]
Okay, we would need to create a "login" to create the OAUTH session in order to get the feed from a userId since an Access Token needs to be created.

So, my question is how to include the access token within the code, so we can access the feed from the userId

**Comment by potomak** [comment]
You can't _include the access token within the code_, see #5

**Comment by jaarong** [comment]
I'd like to hire someone to add this functionality since I'm kind of new to javascript, would it actually be possible to pull in a my instagram account's liked photos to my web site?

**Comment by Deelite310** [comment]
I actually figured it out.   You just need to create a Client (get your client id, client secret ) and you can use it with this script.

http://instagram.com/developer/

Once you get your client information, you have to find out what your User ID is:
http://yvesvanbroekhoven.github.com/get-your-instagram-user-id/

I can post what I did, but the code is at work (*note to self to place in a repository that is accessible from other locations)

**Comment by jaarong** [comment]
Yes, posting your code would be great.  I'm having a hard time following the OAuth stuff and how it applies here given that I can't just put the client secret in the js so that the visitor can see it.

**Comment by jmtmay** [comment]
Any update on this? I'm having the same issue.

**Comment by yvesvanbroekhoven** [comment]
Hi guys,

I've just wrote a small tutorial on how to get an access token & client id for showing your personal Instagram feed:
https://github.com/yvesvanbroekhoven/get-your-instagram-user-id/wiki/How-to-give-a-jquery-instagram-access-to-your-personal-Instagram-feed

**Comment by jelled** [comment]
Here's a simple web interface for obtaining an instagram access token to use with this script.

http://jelled.com/instagram/access-token

**Comment by ghost** [comment]
Hey guys,

First of all, many thanks to potomak for the code. I just want to share how I made it work on my site (I havent finished it yet so I cant post the link. Sorry.)

By this time, I presume you have already registered a new client: http://instagram.com/developer/clients/manage/.

You will need the CLIENT ID and REDIRECT URI to make it work. You will also have to get your USER ID. I got mine without logging into <a href="http://yvesvanbroekhoven.github.com/get-your-instagram-user-id/">this</a> by going to <strong><a href="http://statigr.am">http://statigram</a>/my_username</strong> and clicking one of my photos. If your profile is set to Public, then you should see something like this in the address bar:

http://statigr.am/p/327652845197019654_21441873

The numbers after the underscore _ will be your user id.

Now for the main part.
1. Copy and modify this <strong>authorization URL</strong> <code>https://instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token</code> with your CLIENT-ID and REDIRECT-URI. (Taken from the <a href="http://instagram.com/developer/authentication">Client-Side (Implicit) Authentication section, step one</a>)
2. You will get something like <code>http://your-redirect-uri#access_token=21441873.m6j7321.73z2d5l1m6j73215b8c00l2181x109c5</code>
3. Use that access token.

That's it. Hope it works for you too. :)

**Comment by vprofeta12** [comment]
What is the exact access token, and where do I place it within my instagram.js file or the code on my index page. I have the access token I just dont know what to do with it. I tried pasting it into my code but I keep getting

meta: {error_type:OAuthParameterException, code:400,…}
code: 400
error_message: ""access_token" URL parameter missing. This OAuth request requires an "access_token" URL parameter."
error_type: "OAuthParameterException"

**Comment by vprofeta12** [comment]
bboybulate, What do I do next?????

**Comment by ifollett** [comment]
For those who come across this thread you place the token in the initial function call like so:

``` javascript
$("#instagram-feed").instagram({
    userId: 'YOUR USER ID HERE',
    show: 2,
    clientId: 'YOUR CLIENT ID HERE',
    accessToken: 'YOUR ACCESS TOKEN HERE'
});
```

**Comment by potomak** [comment]
@ifollett it's wrong to expose your own `accessToken` publicly.

**Comment by ValeryCC** [comment]
How do you show a feed of your own account on your website? Why is this so hard?

**Comment by potomak** [comment]
@valerita you can't without exposing your access token and it's so hard because that function of the API is not public.

**Comment by ValeryCC** [comment]
So does this mean it's impossible at this point?

**Comment by potomak** [comment]
It's possible to show a list of photos by userId, but you can't show all your photos using only client side code in a secure way.

**Comment by betron** [comment]
The only other work around I saw was by tagging all your photos with a unique hash tag and then pulling the photos onto your personal site by that tag. The problem is, you will display other user's photos if they happen to use that specific hash tag, as the service grows the chances of that only increase.

**Comment by ValeryCC** [comment]
Wait, it's possible to show a list of photos by userID? I don't mind not showing all of my photos, as long as I can show something from my feed. So far this is what I have:

jQuery(".instagram").instagram({
      userID: 'user_id',
      show: 2,
      clientId: 'client_id'
      });

And the result seems to be completely random images that are not my feed at all.

@betron, I thought about that too, but yes, if someone starts using the "unique" tag, it ceases to be unique.

**Comment by potomak** [comment]
@valerita see https://github.com/potomak/jquery-instagram/issues/11#issuecomment-7479253

**Comment by ValeryCC** [comment]
Sorry I'm being a pain.  I definitely cannot create a plugin, so thank you for your efforts.

I just wonder how webstagram is able to show your own feed on your website so easily.  No need to sign up, just supply the username.  http://web.stagram.com/tools  The only thing annoying me with webstagram is that when a user clicks the image it goes to webstagram instead of instagram.  It'd be perfect if this plugin and webstagram somehow meshed together.

**Comment by potomak** [comment]
I think Webstagram is using server-side authenticated requests to Instagram to get the photos.

The real question is: which token are they using if you can see photos of any user without requiring authentication?

Possible answer: they're using an access token from one of their authenticated users.

Maybe you should ask Webstagram (@jmworks), I'm also curious about their solution...

**Comment by betron** [comment]
Could you explain why it's dangerous to display your accessToken publicly? I'm tempted to just do it, but afraid of what I don't know.

**Comment by ryanburnette** [comment]
If you reveal your access token publicly then anyone can just grab it out of the script and access the Ig API as you. They might use it in some malicious way which could cause you to lose access to the API or get your account banned.

I've been racking my brain looking for a way to show Instagram photos by user ID using a client-side script, but because of how the API works it just doesn't seem possible.

My solution is probably going to be that I'll set up a little cron job that stores the data then use a client-side Ajax call to my own repository. It's a convoluted solution but it's the only thing I can think of to do. To end up with the final goal of an Ajax-based Instagram feed by user ID.

**Comment by bhouse044** [comment]
@bboybulate that works perfectly :+1:
