### ISSUE TITLE
Access token & client id check inconsistent with comment

### ISSUE THREAD

**Issue by AnSavvides** [potomak/jquery-instagram#43]
I am referring to the following [part of the code](https://github.com/potomak/jquery-instagram/blob/master/src/instagram.js#L15):

``` js
if (options.accessToken == null && options.clientId == null) {
  throw 'You must provide an access token or a client id';
}
```

The error message suggests that you must provide an access token _or_ a client id, however in reality the code itself has the _and_ (`&&`) logical operator. So, either the error message should read `'You must provide an access token and a client id'`, or the code should be updated to use the _or_ (`||`) logical operator.

Which one is correct? I am happy to open a pull request and update this accordingly (obviously following the contribution guidelines).

**Comment by Mac-B** [comment]
This to me looks like it already has the correct conditional,

One of the two must be set, 
so if both are in fact null,
then neither of the two were set, 
meaning this error message is the correct one,
Alerting the user that he/she needs to include at least one of those two parameters.

**Comment by potomak** [comment]
@Mac-B is right, if `accessToken` _and_ `clientId` are `null` than you didn't provide `accessToken` _or_ `clientId`.

**Comment by AnSavvides** [comment]
Fair enough, I guess it is open to interpretation, but as an end user if I did not provide an `accessToken` nor a `clientId` (i.e. both `null` or `undefined` since you are not using strict equality) and I got an error message saying `'You must provide an access token or a client id'` that implies to me that I simply need to provide _only one_ of the two, _not_ both which is misleading.

Anyhow, if you are happy with that then I am in no position to claim it is an issue :) Thanks for taking the time to respond though, I appreciate that.

**Comment by potomak** [comment]
Thanks for your comment and for your participation but it's not about interpretations, it's logic.
If you're not sure about the implementation just add some tests to prove I'm not right, see also https://github.com/potomak/jquery-instagram/blob/master/test/instagram_test.js#L9-17

_Note about type checking:_ I'm checking only for `== null` because both `accessToken` and `clientId` are initialized to `null`.

**Comment by AnSavvides** [comment]
Cool, I might have a poke about once I get a free moment and see if I can convince you - just trying to be helpful really because this is a pretty cool library you've built :)

About type checking: If you are only checking for `null` then you can use [strict equality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_when_to_use_them) (`===`) to avoid [type conversions](http://stackoverflow.com/a/359509).

**Comment by potomak** [comment]
See this example: http://jsfiddle.net/hR4um/

Case 1 & 2: everything is fine.
Case 3: exception, neither `a` nor `b` is not `null`.
Case 4: everything is fine even if both `a` and `b` are useless together since only one will be used.

About type checking: I know about type conversions issues but again I don't care about them because `accessToken` and `clientId` are initialized to `null`.

**Comment by AnSavvides** [comment]
Ah, I knew it was all about interpretation - the problem here was that I just interpreted the code _wrongly_, so 100% my mistake. You are absolutely right. Thank you for taking the time to respond :)

**Comment by potomak** [comment]
It's been a pleasure, I'm glad you spent some time reviewing my code.
